[project]
name = "comfyui-autoprune"
description = "A slightly cursed ComfyUI custom node that creates pruned copies of images without ComfyUI metadata."
version = "1.0.0"
license = { file = "LICENSE" }
dependencies  = []

[project.urls]
Repository = "https://github.com/Deathspike/ComfyUI-AutoPrune"

[tool.comfy]
PublisherId = "deathspike"
DisplayName = "ComfyUI-AutoPrune"
Icon = ""
